package data

// The two tables below are snapshots of upstream sources, regenerated by
// running `go generate ./pkg/engine/data`. Both generators reach the network,
// so this is a deliberate, occasional act rather than part of the build.
//
// Each generated file records the exact upstream version it came from in its
// header, which is what makes a stale snapshot visible instead of merely
// possible. Regenerating is expected to produce a reviewable diff: new TLDs get
// delegated, and each Unicode release adds confusables.
//
// Keyboards (keyboards.go) are not listed here. That table is computed from the
// physical layouts by checked-in code rather than snapshotted from anywhere, so
// it has no upstream to drift from.

//go:generate go run ./gen/glyphs -o glyphs_unicode.go
//go:generate go run ./gen/tlds -o tlds_iana.go
